language: java
jdk:
- openjdk11
env:
  global:
  - AWS_ACCESS_KEY_ID=
  - AWS_SECRET_ACCESS_KEY=
  - secure: V6G+YytFd/xB26nsvg/4zHTIencV0xgsve53ojfMjkQkkvrzXswZiVfCuatdPEx9iG6E+v8WAk5jJD3K+puJq6h1ohVhGvHxwRQQjoJWns+5HgXjg7y/Qn3kshiU3hwFmEVpqFsxoNxZrrVKroLS93cIz4wrhx6Edhla50K1xptlNSAf10O1QDpck9jN3UBzj4B1854xIJiXq3qshw/eC8Qu4K3e+lYxzUZ9N9Z8OcL2nyiE4A9lFAuiO0cNov8nqbE2WJwiLJG8ohqEeIOiAfQ2dZISDA3RGVuBfzKOYvXWPshmshX1dXVucMPhtjBRYgJLuKrQACkXMIeTMOhXQ1MP2RtsLWYrH5YALTfVV8fQqzkID+iE167pny3SleVvXbZ0FkzbSYOxXgfr21izD5bQlBIN1dqA2xIIjPXf6i622baEwXe0A9Poby7llr6HlGfmwaesxmu1oNQMf9EsU4HmjNZ6QGjNrMvYpDiK8uoKA+P7SarZPmQpI2Jb1t0BYVnsl4tYpGjtN/KpcX+cG9CIARcHTFUUVeqxtr8bZddCwfJFfRszRyWBK5TD+j9qaJoYGqg57uTHcRLQLh5a+CIVJHe6Jksy8+tXqmoCycCgQEAozQqHCQsCsv/7s5aKMIrrbUo4mOez0gF2g+yUji4jx+hb04y6+JmI8Z9Rk3A=
  - secure: t1RI8aWMqTNuk7CoEcDT8KIpiX0h7YuYEbI+k4HrbNsQ8kAifncdu7s835wYC8OUEE7KZl5srZJx3vnLqbati2Q6Y7pfhO2m+BPalXadEAedhLf13V33R7ESbxbnbjoP+Vd3CDAqWeZHQ/5G3wAWS3wlIFZkD425BNyJZFdP9GAdPugMXu4r9nEqzX2EmLCIRNNc83qS1HDWzzP9s+x3Lr6zGoMG4HmCHdtkgxlHOBAPqVWxb4Aq8lQGmibNBQTYJXmDLm2jZoeWaRDJG2n56GRprvpLjB+B2WB+2KZk15i8ShjhJwS9+p2eJygu69QYoZjFnznl5C6IEHzW5sflKMtA8TBoKC8oHgUEbPaxmh91Xb4R/5CHOpfIUmpyknNusdSVMG9M89bWln6OjAVRA4qLO050U0YhB1GqtREYsKPPF6c4Ji4nIfHL6DzIanvplqHzq5mx5GHmt3hm2YpPo7uWWnPv3VywqgepMGYEl0TObZfBvK2wmyWIZcpr6R+ClwYF+k8GnJhTwzRj6dKQ3qnVLc74MdlUYOAFaV6TbBcNJRFAMg3jyi/XLTHvzdsFvcXPA1Q/HaU6SL9FE/HwFEe0pMvKKRG6vjQBMbVdpymHgbdz8OdYBq5ibVRMNNN5GRdIJat3ikr/QDInLUMRLOuFAncgosP9FmmD9QAvP6Q=
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew sonarqube"
deploy:
  if: env(AWS_ACCESS_KEY_ID) IS NOT blank AND env(AWS_SECRET_ACCESS_KEY) IS NOT blank
  provider: script
  script: "./gradlew publish"
addons:
  sonarcloud:
    organization: bnc-projects
    token:
      secure: VTMTNgZf6UO7Zz1Y5a6jt8jjW3v33jxhE2+thTLud17zdqx6Gj6ujG3OaWbl4qoOYm2T1j5CpEmhYdLPBr0lyLXI7WmsDqeDEHrmQxCWQPguq0D4JfAQhHtjYtk+P8q4ddXP9Zq8I5dcKBARkxS8VPdQ/HXzN6N+jbhn+8ew8/38mrpu/yx7F4c2o9bCCcRKEhuOhozGUHkhzrB0wAGsOFQpKI+nn5MW4YkO2gO5pTCr+Hg23BrVO5ajASQyF2xWkmbjA0QpdSjKjo+K7K4nhL31QI/+zbuLLYglxSNnZXrTR82qPLLGl2YeSQ24ZUzLpvaCXQedXPfrAcU45XlBsxR35qyZBBmp1VOOR8JkgcMKMYd/eu2WBDXuNFSY/3U18AY8D3f1SiHQUFo5Bz3IwcuEHqbU/uv2TU2eT7JR3LY2l63ZGfOclpLyaYhk5QixSaj56ce2cwWWZYyJd9LpWnC9TZMfLoVGuIzwzn5SB1jyAuIuHlhS60B1x5/O3QvyVtwQTVMasbtAh8UeUWvWjfvQFUih3U3HUfa+FAbXR8RhJoiz3wBtYSMwqzMES0Edcr0hsCS9iN9DmKMOslmm4oL+81Vl1syw9HuvvC02+kKnEHbURHrMt5WEKhT+XxQQmKVn4O2J4vvXh7eqofnMsOXVuuebkeKdJKe3iCKXNSM=
notifications:
  slack:
    secure: H8gfDCUw7GeMZhkGQyntWInFazgu+vvSn0r99o9XcSrKQHVhDinf2Z1asKuBUv/Vy/fBxvelInFnaTAzVrXtcQoueOLwm4STyDhU+P0+pcmxLvxnGucYOq2OD66RjPojeu2v09E8QG79MIip2hPVQ6e02v7AcG6k41rSYMS6fphHqq7N4Lp5LA1wlPhQa/t+e9d5rvBEJoO4dhjjaFPd9ViHjFIYeF9zfHFQoy+GPVZLLlAUz/QAeAxfXs8RjVjZZTKgt5QxbYcWAJjUj5ouAm02w4C2QcRbMAaP0nBgvIEY+vXVnQKDna6L0tgs8XwFK7HLUGh0UXC4nj4ShTCUycGEVuKjngIbrs3F8L+pkdgwieoQlHeAYHulcTyhfuZq02zd/owfHHZwx+Ru3zUd7lbfuCWYfwWLgBbs3j6K5mwQ78bm45+G14qkB0FkVdgmtbPa/jxU9FZF/NmCE1qa2EKJAShqSR3dy/491MY8euZLiEePe4RpcLMqo18tkbCJMrDsMO4hk3Jv/+ne7iDV6XOAWhvmJGaI58/mIKQ6dkZXE74z812FbBHKhtAY1WFlugzqTGXexdMXW6na+5baXTTDN8T4OA5PlIzgUOQ3USUJW/HnjIHrutuj6mHe5cw9R2Er/amHLEpcnKlxNp2pC19rdsMsv0xgnlJnmjCQazc=
