language: java
jdk:
- openjdk11
dist: xenial
env:
  global:
  - AWS_ACCESS_KEY_ID=
  - AWS_SECRET_ACCESS_KEY=
  - OPERATIONS_ROLE_ARN=
  - secure: TW+TImnf4iCaDIG6pd2xJ4ninnNGixo1XDLZ4gpR/zFvMi5vRKShXps+faCzOXKaulVQdyAHM7XvinxcI/+RRn0a7h0DimnHFFkqSAaRgLQXMzErg6Z/nVmMcHlbMkR2uaigHHsIDqNIYlhQGkgF1Ejj51qmwlqBKwNlYD78pFcjWl9UW81WClwQ6uNQU2XcsCROB64rPTJC3/gqcqohSbljKwVUD4oSK6tPNNYWC+7+JeqhFzmMRuSph+q4JyfRJ3g585ndnREh0SLYfF3ftZMTDMiD0/MRiQ46sjSWIpQcER7wT7M9ddto8w2YPobr9W2gnikKDNNJviKueLcvNw8MUTk9xwqmJ0VTX3XaWBdhJCKzVm4Xc8Yt/GzcAe1imRzlGX+qi+3GKh+973A6i0Mi6khRL6byqrQQFQaz1PMelLixkbbI/gY9iNexayHeOzRVIH2EeKJQonTzx3sVShdeEA64MP9bmv+PrwFsBEjBnalVaX7Ictf4mAV4EYsjnodNFPPk7iiz2w71oBPUPwN/Y8U0vEZXsoZr7JGfFNE60qrdKOATVsA6WZT/ZF755qGK7sP7PYj1n3AgptCSGFldJkUv0lnhyumkqnJ8/WK/Ojt+9aVAtiwQxfncNPiyXI4Tpa++zkqkFij1eeeohBsftLM5irapkpLurGdOtCc=
  - secure: Ke39MmwAAxpwLYf81gkF2lXgf3WWiEPNiLz+Jg9vMHD2K5+I8hQ8hdULt6z5eliBsT+A9YoAkJfkOvhLN1KHP+7PGjs3Ou1JHKQV+Onw4xOTS5eA6ObEW6cViY2gxwz48iihRFyidzG+vH5oj458zGTS2ntyUzCyUC12nbLQzJTGtFlMoQsK9IIp6gl2WYhOkV8jh1AuGnD7ydSANpnZsdTUX4Nd3A93IRXbOgk/be+CIWr+uFWqwgFnQIRbWvhDS1h5QTj2YJRXWqYAyjUKQj6eJ6ceBuxUd0h/Ln51z1r7LBykCIF8lu8JEIaX6zFwVNJR6gFOE9cF8galPhytS3jmSBrfYjFkwUN5wep56aYt33/sy5kCSa5wzbtdjHHGuVv0WD/hn7wFoa8625bOCgptR8CIHnBv9l924FWw+ZjNskfTtDj+03YxLV5Z1D4DBcW6zwa4xjmLBjFqbGT3inn2GY5NkHIlIPLdChh/DC2/NvAl0HOuS/JwsgQ2fXRi7p0ef/vUhf8a/g3o6RH5j8/nFLan0+DdeIMoStRt6XM7IC5ze0BvV6EdIm/d73YdAh28ap2WQvPYl2V30uWfeozAWFBPP6iBTszWc6AsYtUMYiVBMg1RB7BhPw42ukrBT18G0D2UMlYjRTtCus0dgeUwFX+vvjBl2DFu20UUSVE=
  - secure: cOfrA/tF86HhyudZcZzu+8BL8K6pIQModHm6NpkdbDTNPv3RdWIJQygnuK7qKtZwejT5O8RCVhST6AQcfQ1iJSl7OWNjEemPtuayqvt52TPtbxIOY6xV30PEBnQ+iCwQ1lR19VRIHw++M4FREeXeHSQW/mbGmoojCZuu7ezDp8fgNImt5AJTvOuK4DzfUgf0jxJfszJX2b/UYIM1PiZJo0EmWzjp5M6bN/l2Sn3pBLNJkVwuXi8Nvy7Ej0+EKCmWyvESnrdQcOZoWHu/TtW3maSmpnJpBkl4fDzQRv1nUtac/YInF8Mee8LMJVOaVx2dhdmBuKMdlNDcgwQcUvVPKudDuF6llI9ZhGtHVbcxb5ke/YyQzONwclvx7Qg9mGkcraZfJVkjz5rGw9x4iz6y8/sc+giuyIDFyS8V0dcx8BomZU+y+/QyXeJGAduKbOgo7OSTm6qhaFt2bkMk4Tw8Ew2DfDYokFSRl0xEkCOy/YEvsA3Z4lFBtLa4HuwHL3HjKEWq8nA3PgnfYx1sqe9grrEHqzXmuArwFso7LWje+A57roP1xXUvsDqFJ8o9zM/EUNM9r7wkx9n0Di57z7iDi6dZoi17Ts9WIZZD9h6OXMbv58AFozjqn8oEFjvLEDnbNE6fP9q9e7o6PvMP6Kyt9DsAMAai3DCtxneyFAM/HoI=
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- eval $(aws sts assume-role --role-arn "$OPERATIONS_ROLE_ARN"  --role-session-name "TravisCI" | jq -r '.Credentials | @sh "export AWS_SESSION_TOKEN=\(.SessionToken)\nexport AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey) "')
after_success:
- "./gradlew sonarqube"
deploy:
  provider: script
  skip_cleanup: true
  script: "./gradlew publish"
  on:
    all_branches: true
addons:
  snaps:
  - name: aws-cli
    confinement: classic
    channel: latest/stable
  sonarcloud:
    organization: bnc-projects
    token:
      secure: VTMTNgZf6UO7Zz1Y5a6jt8jjW3v33jxhE2+thTLud17zdqx6Gj6ujG3OaWbl4qoOYm2T1j5CpEmhYdLPBr0lyLXI7WmsDqeDEHrmQxCWQPguq0D4JfAQhHtjYtk+P8q4ddXP9Zq8I5dcKBARkxS8VPdQ/HXzN6N+jbhn+8ew8/38mrpu/yx7F4c2o9bCCcRKEhuOhozGUHkhzrB0wAGsOFQpKI+nn5MW4YkO2gO5pTCr+Hg23BrVO5ajASQyF2xWkmbjA0QpdSjKjo+K7K4nhL31QI/+zbuLLYglxSNnZXrTR82qPLLGl2YeSQ24ZUzLpvaCXQedXPfrAcU45XlBsxR35qyZBBmp1VOOR8JkgcMKMYd/eu2WBDXuNFSY/3U18AY8D3f1SiHQUFo5Bz3IwcuEHqbU/uv2TU2eT7JR3LY2l63ZGfOclpLyaYhk5QixSaj56ce2cwWWZYyJd9LpWnC9TZMfLoVGuIzwzn5SB1jyAuIuHlhS60B1x5/O3QvyVtwQTVMasbtAh8UeUWvWjfvQFUih3U3HUfa+FAbXR8RhJoiz3wBtYSMwqzMES0Edcr0hsCS9iN9DmKMOslmm4oL+81Vl1syw9HuvvC02+kKnEHbURHrMt5WEKhT+XxQQmKVn4O2J4vvXh7eqofnMsOXVuuebkeKdJKe3iCKXNSM=
notifications:
  slack:
    secure: H8gfDCUw7GeMZhkGQyntWInFazgu+vvSn0r99o9XcSrKQHVhDinf2Z1asKuBUv/Vy/fBxvelInFnaTAzVrXtcQoueOLwm4STyDhU+P0+pcmxLvxnGucYOq2OD66RjPojeu2v09E8QG79MIip2hPVQ6e02v7AcG6k41rSYMS6fphHqq7N4Lp5LA1wlPhQa/t+e9d5rvBEJoO4dhjjaFPd9ViHjFIYeF9zfHFQoy+GPVZLLlAUz/QAeAxfXs8RjVjZZTKgt5QxbYcWAJjUj5ouAm02w4C2QcRbMAaP0nBgvIEY+vXVnQKDna6L0tgs8XwFK7HLUGh0UXC4nj4ShTCUycGEVuKjngIbrs3F8L+pkdgwieoQlHeAYHulcTyhfuZq02zd/owfHHZwx+Ru3zUd7lbfuCWYfwWLgBbs3j6K5mwQ78bm45+G14qkB0FkVdgmtbPa/jxU9FZF/NmCE1qa2EKJAShqSR3dy/491MY8euZLiEePe4RpcLMqo18tkbCJMrDsMO4hk3Jv/+ne7iDV6XOAWhvmJGaI58/mIKQ6dkZXE74z812FbBHKhtAY1WFlugzqTGXexdMXW6na+5baXTTDN8T4OA5PlIzgUOQ3USUJW/HnjIHrutuj6mHe5cw9R2Er/amHLEpcnKlxNp2pC19rdsMsv0xgnlJnmjCQazc=
