language: java
jdk:
- openjdk13
dist: bionic
env:
  global:
  - AWS_ACCESS_KEY_ID=
  - AWS_SECRET_ACCESS_KEY=
  - OPERATIONS_ROLE_ARN=
  - secure: Td6duOWrafFwX+yNZVQ6ndlYZc+Gs6EFHqoea0ceC3EX1iPzkJBj0h7iWhDgciOIccBGficcyVjA4FTovUBMs7xtifkzqscv9XAOg193s49Yf7qrv3R+9rBo9C9qMGbYM/UVhXqk1/IPdvrWeDKzSBhZc8H6u78cAA8jU8DnmlkCq/jQbqbuOl5szND90QBUtc8LQ7ZSgz86GnJxxhyA4sllHru6Z3ysv6mS5fvmy32s2s1BODWaet5lk00Xv1th0lLO1P1quYIMqlS2kXnbvWWgSyEzRuncb3tvuz0UPTwDCj3RRAIbbC8GO89+pmJsT6k/nS3H9yjTC7o/DagpSP5UaftqGrrUGSwgntAoxMqiNUnGkr7xMbhvTID0tGjCFUxTmcpkOi4kpBO+sAYi0FUQObcgRFzDPK7FdNURyGH4D0w+urDoUb+6AnyPaviOOvSl9j4rkpTDMw74fn+t23EB+uwtX4+T4G1afVNH2MQc0I7RieNd6+JV0yNewtvrUc9garp8znw6VElOoKglVCZdPCglYj4NGLemD9HyCJebbn7awtUlVpMxmTr65d4H+aPjd3uKmBoqDEWsYanwLwQV0vxlX2oFpwmrv4ZoNR1tcVKYlvASFQYovEfcvW8Bg0n+LNSQAHlCy/ZWwLvyMhgaGJJ+dzNx+cbUjIq7Kgs=
  - secure: fEE+BtGRYWmJLYALmAAAvXzuvxUF/sG5kBBCxnQuEkQC7Y+Na1Zb2/8Tbqrdkze/4wiZzrkqrcJFfQmaqxWEfqC7TD719AySVJQ0XzljvrAU5i4IXFe41r2icw/wBhB4NLG/EHaanVMAzW8Y2hGfwvHMVHauRO78pbpVWMP2lnN2oAQufKNEqe4Q8nEcIxn3Hx7jdZcPKVYqfN+qjsF8D/PWa5mmfppgOwPVjms07Iyy+nI9sTiKU/k8EyhuouSqBAAGT5HbpNO6WnjlVfxG7nAkin9ustNdEGrV5GO3KNIAT6STeKip0/Nh8rIxv9QRKBqKorbdAGdBtOXlaR7zgXh5ZpLVNG4LRZUBW2Y7mMoFOAOsPVwRALgPmJQSoSPheNUPTp6T73mf5JjR9F0Fn68VmLjQwE6l81m+6Tfm4aqRS+An6FLg8+k3KaZ71PBrCzsR55/3sPmHK9zoAJ+WLgY8bJ7UGXyiz7SKpifYK5sW4AAoRSJAw5+vvEJMu/i3qe47uALl7HzXvvOkp4bn53VGjTYIVWkzzWA0a3Jyr1YSVOB4sX/Jz0j8KSiwJZFto9GIMZRRalHoNqvz2x0bwBw4sQ3dLOD1+T3kIpYqGPvtH3i5IYrCTAxL2h0BFlRbfhaXrORIoga1eD0f1VYEL3sOvZC+wOayY64QlNZZ+8k=
  - secure: QIOu6fQ1inEjFIPDeJfWKj7bjWDN5/ISRql5dorTsqP3aoSvZ4iRctcdDkZ48FpftntC3MqAJ8hK75v3f29J+YGf5dvpa1UHtuNJGUJXGYp0svmnfAf9C44hgrmcX9ItzJ+IFbuihSxJcdSiruR5E07nmgex99evRn3fXkllY4vGJeynItLTrLrkPmYlCVTydcYBP6jzM3GX2ls137n6RFiRbJyC6DKkqHdsWGpWP5Z6kNknP8UZp5twQlKwIb9er4tJeVBpIPsOYZ/VD4af4GQlgZTKXhy4E0AiOmmNBcPl+w9P8mT1du3crzglIfUYG3DGkENMRbW28kz+AIjeRYzJZrtRN7DPMaEZrhOBS0nxABe+L1g0ZLd+NuC2lLCwR9R+V/RpJf36/CgD/SlIkHWucZHrg0vPBi9HY+73IZVE85jeaSaOB3NmZ3Z9VLTaHLR5CS7elvRsOZtFf3sx0gvGqNXdC1HPHYQp0RUmDfETtGkByqjoTYWMbi1LFRBFAT2UOGype5Rm8WL2S0o2j0/4RJbmJZmlQ82JjUVfe81KMSxfYVoMkj4ROTjDegruNqj5+xfO8YDCAx3IWyq7hZxCHot/d4uIi6TXCyeM/cnAyLrL5gOY+Kvfw7bOnJvZB/+Sjad0Mm/2JDxm909EraSfU6CO1w5NqPkJS4PEpW0=
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- eval $(aws sts assume-role --role-arn "$OPERATIONS_ROLE_ARN" --role-session-name "${TRAVIS_REPO_SLUG//\//-}" | jq -r '.Credentials | @sh "export AWS_SESSION_TOKEN=\(.SessionToken)\nexport AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey) "')
after_success:
- "./gradlew sonarqube"
deploy:
  provider: script
  skip_cleanup: true
  script: "./gradlew publish"
  on:
    all_branches: true
addons:
  snaps:
  - name: aws-cli
    confinement: classic
    channel: latest/stable
  sonarcloud:
    organization: bnc-projects
    token:
      secure: VTMTNgZf6UO7Zz1Y5a6jt8jjW3v33jxhE2+thTLud17zdqx6Gj6ujG3OaWbl4qoOYm2T1j5CpEmhYdLPBr0lyLXI7WmsDqeDEHrmQxCWQPguq0D4JfAQhHtjYtk+P8q4ddXP9Zq8I5dcKBARkxS8VPdQ/HXzN6N+jbhn+8ew8/38mrpu/yx7F4c2o9bCCcRKEhuOhozGUHkhzrB0wAGsOFQpKI+nn5MW4YkO2gO5pTCr+Hg23BrVO5ajASQyF2xWkmbjA0QpdSjKjo+K7K4nhL31QI/+zbuLLYglxSNnZXrTR82qPLLGl2YeSQ24ZUzLpvaCXQedXPfrAcU45XlBsxR35qyZBBmp1VOOR8JkgcMKMYd/eu2WBDXuNFSY/3U18AY8D3f1SiHQUFo5Bz3IwcuEHqbU/uv2TU2eT7JR3LY2l63ZGfOclpLyaYhk5QixSaj56ce2cwWWZYyJd9LpWnC9TZMfLoVGuIzwzn5SB1jyAuIuHlhS60B1x5/O3QvyVtwQTVMasbtAh8UeUWvWjfvQFUih3U3HUfa+FAbXR8RhJoiz3wBtYSMwqzMES0Edcr0hsCS9iN9DmKMOslmm4oL+81Vl1syw9HuvvC02+kKnEHbURHrMt5WEKhT+XxQQmKVn4O2J4vvXh7eqofnMsOXVuuebkeKdJKe3iCKXNSM=
notifications:
  slack:
    secure: H8gfDCUw7GeMZhkGQyntWInFazgu+vvSn0r99o9XcSrKQHVhDinf2Z1asKuBUv/Vy/fBxvelInFnaTAzVrXtcQoueOLwm4STyDhU+P0+pcmxLvxnGucYOq2OD66RjPojeu2v09E8QG79MIip2hPVQ6e02v7AcG6k41rSYMS6fphHqq7N4Lp5LA1wlPhQa/t+e9d5rvBEJoO4dhjjaFPd9ViHjFIYeF9zfHFQoy+GPVZLLlAUz/QAeAxfXs8RjVjZZTKgt5QxbYcWAJjUj5ouAm02w4C2QcRbMAaP0nBgvIEY+vXVnQKDna6L0tgs8XwFK7HLUGh0UXC4nj4ShTCUycGEVuKjngIbrs3F8L+pkdgwieoQlHeAYHulcTyhfuZq02zd/owfHHZwx+Ru3zUd7lbfuCWYfwWLgBbs3j6K5mwQ78bm45+G14qkB0FkVdgmtbPa/jxU9FZF/NmCE1qa2EKJAShqSR3dy/491MY8euZLiEePe4RpcLMqo18tkbCJMrDsMO4hk3Jv/+ne7iDV6XOAWhvmJGaI58/mIKQ6dkZXE74z812FbBHKhtAY1WFlugzqTGXexdMXW6na+5baXTTDN8T4OA5PlIzgUOQ3USUJW/HnjIHrutuj6mHe5cw9R2Er/amHLEpcnKlxNp2pC19rdsMsv0xgnlJnmjCQazc=
